version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:4.2.2-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=codis
      - RABBITMQ_DEFAULT_PASS=codis
  db:
    image: postgres
    volumes:
      - ./api/migrations:/docker-entrypoint-initdb.d
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: codis
      POSTGRES_PASSWORD: codis
      POSTGRES_DB: codis
    ports:
      - "5432:5432"
